# coding: utf-8

# flake8: noqa

"""
    Kroger API Reference

    <br> <div style=\"background-color: #ffebb2; padding: 16px; border-radius: .25rem; border: 1px solid #ff8d00; padding: 8px; font-size: 13.5px; padding-right: 12px; padding-left: 12px; padding-top: 14px; padding-bottom: 14px;\"><b>DEPRECATION NOTICE</b> - As of 06/01/2020, the Coupons API is no longer available. Currently, there is no direct replacement for the Coupons API.</div>  # Introduction The following APIs are publicly available to allow new clients to build products,  services, or customer experiences that leverage the unique data, functions, and  applications of Kroger. As a company that strives to empower the developer community  and meet our customers where they are, we are offering these APIs as the first  step to building an ecosystem that promotes speed, simplicity, and security. <br><br> To begin using our Public APIs, see the [Getting Started](https://developer.kroger.com/documentation/consume) documentation.   # Environments  During registration, we require apps to be registered for environments individually. Use one of the following paths based on the environment you selected for your application during the registration process.  | Environment | Path | |-------------|------| |Production | https://api.kroger.com/v1/ | |Certification | https://api-ce.kroger.com/v1/ |  # Authentication  For API authentication, Kroger uses the OAuth2 protocol ([RFC6749](https://tools.ietf.org/html/rfc6749)),  supporting the Authorization Code, Client Credentials, and Refresh Token grant types. If you're unfamiliar  with OAuth2, see our [Understanding OAuth2](https://developer.kroger.com/documentation/consume/guides/understanding-oauth2)  documentation.   <!-- ReDoc-Inject: <security-definitions> -->   # noqa: E501

    OpenAPI spec version: 1.2.1
    Contact: APISupport@kroger.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.cart_api import CartApi
from swagger_client.api.identity_api import IdentityApi
from swagger_client.api.locations_api import LocationsApi
from swagger_client.api.o_auth2_api import OAuth2Api
from swagger_client.api.products_api import ProductsApi
# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.api_error import APIError
from swagger_client.models.api_error_auth_server_error import APIErrorAuthServerError
from swagger_client.models.api_error_auth_server_error_errors import APIErrorAuthServerErrorErrors
from swagger_client.models.api_error_cart_ok import APIErrorCartOk
from swagger_client.models.api_error_cart_server_error import APIErrorCartServerError
from swagger_client.models.api_error_cart_server_error_errors import APIErrorCartServerErrorErrors
from swagger_client.models.api_error_departments_id_bad_request import APIErrorDepartmentsIdBadRequest
from swagger_client.models.api_error_departments_id_bad_request_errors import APIErrorDepartmentsIdBadRequestErrors
from swagger_client.models.api_error_forbidden import APIErrorForbidden
from swagger_client.models.api_error_forbidden_errors import APIErrorForbiddenErrors
from swagger_client.models.api_error_identity_server_error import APIErrorIdentityServerError
from swagger_client.models.api_error_identity_server_error_errors import APIErrorIdentityServerErrorErrors
from swagger_client.models.api_error_locations_id_bad_request import APIErrorLocationsIdBadRequest
from swagger_client.models.api_error_locations_id_bad_request_errors import APIErrorLocationsIdBadRequestErrors
from swagger_client.models.api_error_locations_server_error import APIErrorLocationsServerError
from swagger_client.models.api_error_locations_server_error_errors import APIErrorLocationsServerErrorErrors
from swagger_client.models.api_error_no_content import APIErrorNoContent
from swagger_client.models.api_error_not_found import APIErrorNotFound
from swagger_client.models.api_error_products_id_bad_request import APIErrorProductsIdBadRequest
from swagger_client.models.api_error_products_id_bad_request_errors import APIErrorProductsIdBadRequestErrors
from swagger_client.models.api_error_products_server_error import APIErrorProductsServerError
from swagger_client.models.api_error_products_server_error_errors import APIErrorProductsServerErrorErrors
from swagger_client.models.api_error_unauthorized import APIErrorUnauthorized
from swagger_client.models.api_error_unauthorized_errors import APIErrorUnauthorizedErrors
from swagger_client.models.authorization_code import AuthorizationCode
from swagger_client.models.authorization_code_response import AuthorizationCodeResponse
from swagger_client.models.body import Body
from swagger_client.models.cart_cart_item_model import CartCartItemModel
from swagger_client.models.cart_cart_item_request_model import CartCartItemRequestModel
from swagger_client.models.client_credentials import ClientCredentials
from swagger_client.models.client_credentials_response import ClientCredentialsResponse
from swagger_client.models.error_model import ErrorModel
from swagger_client.models.id import Id
from swagger_client.models.identity_profile_model import IdentityProfileModel
from swagger_client.models.identity_profile_model_data import IdentityProfileModelData
from swagger_client.models.inline_response200 import InlineResponse200
from swagger_client.models.inline_response400 import InlineResponse400
from swagger_client.models.inline_response4001 import InlineResponse4001
from swagger_client.models.inline_response4002 import InlineResponse4002
from swagger_client.models.inline_response4003 import InlineResponse4003
from swagger_client.models.inline_response4004 import InlineResponse4004
from swagger_client.models.inline_response4005 import InlineResponse4005
from swagger_client.models.inline_response4006 import InlineResponse4006
from swagger_client.models.invalid_access import InvalidAccess
from swagger_client.models.invalid_code import InvalidCode
from swagger_client.models.invalid_credentials import InvalidCredentials
from swagger_client.models.invalid_department import InvalidDepartment
from swagger_client.models.invalid_department_id import InvalidDepartmentId
from swagger_client.models.invalid_email import InvalidEmail
from swagger_client.models.invalid_grant_type import InvalidGrantType
from swagger_client.models.invalid_lat_long import InvalidLatLong
from swagger_client.models.invalid_limit import InvalidLimit
from swagger_client.models.invalid_location_id import InvalidLocationId
from swagger_client.models.invalid_merchant import InvalidMerchant
from swagger_client.models.invalid_parameter import InvalidParameter
from swagger_client.models.invalid_parameters import InvalidParameters
from swagger_client.models.invalid_product_id import InvalidProductId
from swagger_client.models.invalid_radius_in_miles import InvalidRadiusInMiles
from swagger_client.models.invalid_redirect_uri import InvalidRedirectUri
from swagger_client.models.invalid_refresh_token import InvalidRefreshToken
from swagger_client.models.invalid_scope import InvalidScope
from swagger_client.models.invalid_upc import InvalidUPC
from swagger_client.models.invalid_zip_code import InvalidZipCode
from swagger_client.models.locations_address import LocationsAddress
from swagger_client.models.locations_chain import LocationsChain
from swagger_client.models.locations_chain_response import LocationsChainResponse
from swagger_client.models.locations_chains_response import LocationsChainsResponse
from swagger_client.models.locations_daily_hours import LocationsDailyHours
from swagger_client.models.locations_department import LocationsDepartment
from swagger_client.models.locations_department_at_location import LocationsDepartmentAtLocation
from swagger_client.models.locations_department_hours import LocationsDepartmentHours
from swagger_client.models.locations_department_response import LocationsDepartmentResponse
from swagger_client.models.locations_departments_response import LocationsDepartmentsResponse
from swagger_client.models.locations_geo_location import LocationsGeoLocation
from swagger_client.models.locations_location import LocationsLocation
from swagger_client.models.locations_location_hours import LocationsLocationHours
from swagger_client.models.locations_location_response import LocationsLocationResponse
from swagger_client.models.locations_location_search_response import LocationsLocationSearchResponse
from swagger_client.models.meta_model import MetaModel
from swagger_client.models.meta_model_pagination import MetaModelPagination
from swagger_client.models.metadata_model import MetadataModel
from swagger_client.models.oauth2_auth_token_response import Oauth2AuthTokenResponse
from swagger_client.models.oauth2_code_response import Oauth2CodeResponse
from swagger_client.models.one_ofbody import OneOfbody
from swagger_client.models.one_ofid import OneOfid
from swagger_client.models.one_ofinline_response200 import OneOfinlineResponse200
from swagger_client.models.one_ofinline_response400 import OneOfinlineResponse400
from swagger_client.models.one_ofinline_response4001 import OneOfinlineResponse4001
from swagger_client.models.one_ofinline_response4002 import OneOfinlineResponse4002
from swagger_client.models.one_ofinline_response4003 import OneOfinlineResponse4003
from swagger_client.models.one_ofinline_response4004 import OneOfinlineResponse4004
from swagger_client.models.one_ofinline_response4005 import OneOfinlineResponse4005
from swagger_client.models.one_ofinline_response4006 import OneOfinlineResponse4006
from swagger_client.models.product_id import ProductId
from swagger_client.models.products_product_aisle_location_model import ProductsProductAisleLocationModel
from swagger_client.models.products_product_boxed_dimensions_model import ProductsProductBoxedDimensionsModel
from swagger_client.models.products_product_image_model import ProductsProductImageModel
from swagger_client.models.products_product_image_size_model import ProductsProductImageSizeModel
from swagger_client.models.products_product_item_fulfillment_model import ProductsProductItemFulfillmentModel
from swagger_client.models.products_product_item_model import ProductsProductItemModel
from swagger_client.models.products_product_item_price_model import ProductsProductItemPriceModel
from swagger_client.models.products_product_model import ProductsProductModel
from swagger_client.models.products_product_payload_model import ProductsProductPayloadModel
from swagger_client.models.products_product_temperature_model import ProductsProductTemperatureModel
from swagger_client.models.products_products_payload_model import ProductsProductsPayloadModel
from swagger_client.models.refresh_token import RefreshToken
from swagger_client.models.refresh_token_response import RefreshTokenResponse
from swagger_client.models.root_cause_model import RootCauseModel
from swagger_client.models.upc import UPC
